### ISSUE TITLE
Blocked loading mixed active content on Now monorepo v2 with docker prisma server

### ISSUE THREAD

**Issue by maierson** [prisma/prisma1#3886]
I am trying to stand up a prisma server on Now v2 within a monorepo with a yoga server. The prisma server is connected to a mongoDB Atlas cluster. Here's what I have so far:

Dockerfile

```
FROM prismagraphql/prisma:1.14

ARG MONGO_CONNECT // the mongodb Atlas connection string

ENV PRISMA_CONFIG_PATH prisma.yml

COPY config.yml prisma.yml

RUN sed -i s/MONGO_CONNECT/$MONGO_CONNECT/g prisma.yml

EXPOSE 4466
```

config.yaml
```
port: 4466
databases:
  default:
    connector: mongo
    database: my-db
    uri: MONGO_CONNECT
    ssl: true
```

prisma db config - `now` needs `__dirname` to correctly locate the `prisma.graphql` file
```
const db = new Prisma({
  typeDefs: __dirname + "/generated/prisma.graphql",
  endpoint: "http://localhost:4466",
  // secret: process.env.PRISMA_SECRET,
  debug: true,
});
```

This makes the prisma server available at ```http://localhost:4466``` inside the monorepo.
The yoga server is started in index.js which is deployed as such:
(note that `now-cli` does not allow deployment to `v1` any longer).

now.json
```
{
  "name": "prisma-server-monorepo",
  "version": 2,
  "build": {
    "env": {
      "MONGO_CONNECT": "@mongo-connect" // mongo-connect secret string
    }
  },
  "builds": [
    { "src": "next.config.js", "use": "@now/next" }, // react app
    { "src": "./src/index.js", "use": "@now/node-server" } // yoga server
  ]
}
```
What happens after deployment:
The prisma server is available @ http://localhost:4466
The yoga server can connect to it via localhost
When loading the react application:
Chrome - OK - the mongoDB Atlas data is loaded
Firefox / Safari: I get the following Error -> 

```
Blocked loading mixed active content “http://localhost:4466/”
```
This is because of the monorepo connection to localhost via http protocol instead of ssl.

Is there a simple way to fix this short of fiddling with the docker image to add ssl etc.?

What else I've tried:
- ```graphql create hello-advanced --boilerplate node-advanced``` Issue: the downloaded repository does not have any execution scripts in `package.json` and the install process does not offer to choose a prisma server (ie. Demo server) as per instructions.
- now `micro-proxy` to forward to `localhost:4466` but I get connection refused (to localhost:4466) when trying to access the `now.sh` endpoint where the micro-proxy is deployed.

```
const createProxy = require('micro-proxy')
const proxy = createProxy([
  {"pathname": "/**", "dest": "http://localhost:4466"}
])

proxy.listen()
```
It seems that there is no clear working solution yet for deploying a prisma server to `now v2.` reliably. I'm happy to write a detailed explanation with boilerplate once I get this to work.

Also I'd be happy to deploy to Prisma Cloud but the Demo server there doesn't seem to be able to connect to a mongo db (only Postgres and MySql are available options).

Thank you

**Comment by pantharshit00** [comment]
Hi, 

As I can infer from the error it is blocked due to no SSL being used to serve it.

Any reason why you are not using the domain provided by now instead of localhost.

**Comment by maierson** [comment]
@pantharshit00 Thank you.

So this is deployed under what now v2. calls a monorepo. From what I gather it means that you can deploy various code bases and languages (ie javascript, python etc). Each gets its own serverless environment but can be accessed under the same single now public url (ssl encrypted) under different routes (as per `now.json` config file).

The yoga server I have deployed can be accessed at the domain provided by now (ssl encrypted public url). The docker image exposes its endpoint at http://localhost:4466. Putting a /graphql call to the public endpoint gets thru to the yoga-server which in turn accesses the local monorepo @ `http://localhost:4466` to talk to the prisma server which gets its data from mongo atlas. This data exchange is all confirmed so the entire scaffolding works (with Docker). 

The ssl error happens because of the yoga-server accessing the localhost:4466 without a secure protocol and it only gets blocked once the data makes it over to the browser.

I haven't been able to expose a direct prisma endpoint on now v2. yet (in other words getting the localhost:4466 publicly accessible on the now public endpoint). That could be a good alternative. From what I gather on spectrum.chat others are having the same problem. 

The other production issue is the lack of horizontal scaling of the prisma server without using RabbitMQ but that's a different problem for the future.

**Comment by pantharshit00** [comment]
Indeed the serverless support is a bit limited right now but we are working on prisma as a binary. It has been already merged into alpha and I expect it will improve serverless support as we were able to use it AWS lambda. https://github.com/prisma/prisma/pull/3695

I am still not sure that will help now as they have only concepts of builders and no binary execution support ( I maybe wrong here). I will try to find a workaround if I can.

**Comment by maierson** [comment]
Thank you for that link. I'll keep an eye on it.

Now have a node-server builder that is used to put up an entire "legacy" server (meaning not lambda). It should be possible to put Prisma up that way. 

Alternatively if you guys could add the mongodb database option to Prisma cloud demo server I would be very interested to use it and it could provide a path towards a paying account once the concept is validated. Right now as far as I can tell I can only set up a relational db on the Prisma Cloud website.
